"""empty message

Revision ID: 8a697a22a03d
Revises: 
Create Date: 2021-03-01 13:23:21.680166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a697a22a03d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('emailforavatar', table_name='comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('emailforavatar', 'comment', ['emailforavatar'], unique=True)
    # ### end Alembic commands ###
