"""empty message

Revision ID: 8cd80a1a971a
Revises: 1d77d07ad9a1
Create Date: 2021-02-25 12:15:47.408979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd80a1a971a'
down_revision = '1d77d07ad9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'post', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###
